services:
  # ------------------- Ollama Backend -------------------
  - type: web
    name: research-paper-ollama
    env: docker
    dockerfilePath: ./Dockerfile.ollama
    plan: free
    region: oregon
    healthCheckPath: /api/tags
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0

  # ------------------- Streamlit Frontend -------------------
  - type: web
    name: research-paper-frontend
    env: docker
    dockerfilePath: ./Dockerfile.streamlit
    plan: free
    region: oregon
    port: 8501
    envVars:
      - key: OLLAMA_URL
        fromService:
          name: research-paper-ollama
          type: web
          property: host
